export const output = {
  Carrierrow: 0,
  Carriercol: 0,
  Carrierdir: 0,
  Battleshiprow: 1,
  Battleshipcol: 0,
  Battleshipdir: 0,
  Destroyerrow: 2,
  Destroyercol: 0,
  Destroyerdir: 0,
  Submarinerow: 3,
  Submarinecol: 0,
  Submarinedir: 0,
  Patrolboatrow: 4,
  Patrolboatcol: 0,
  Patrolboatdir: 0,
};
